version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8005:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7
    ports:
      - 6380:6379

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - web
    env_file:
      - ./.env

  celery-beat:
    build: .
    command: celery -A core beat --loglevel=INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
