version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A your_project_name worker --loglevel=info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

volumes:
  postgres_data: