# Generated by Django 5.1.2 on 2024-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='scraping_active',
            field=models.BooleanField(default=False),
        ),
    ]
